# FRAMEWORK FILE. Host CLI for the devbox on Windows (bash twin: ./dev).
# Kept thin on purpose: it resolves paths, writes .box/.env and drives
# docker. Everything else runs inside the container (/opt/box/bin).
# If script execution is blocked, use dev.cmd (same arguments).
$ErrorActionPreference = 'Stop'

$Root = $PSScriptRoot
$Network = 'agent-devbox'
$NixCacheVolume = 'agent-devbox-nix-cache'
$MemoryProject = 'agent-devbox-memory'

function Show-Usage {
  @'
Usage: .\dev <command>

  up [--code]   Build, start the shared memory server and the dev container
  shell         Open a bash shell in the dev container
  code          Open VS Code inside the dev container
  down          Stop and remove the dev container (memory server keeps running)
  rebuild       Rebuild images with the latest agents, recreate the container
  update        Pull the latest framework files from the template repo
  init <path>   Copy this template into an existing project
'@
}

function Fail($msg) { Write-Host "dev: $msg" -ForegroundColor Red; exit 1 }
function Info($msg) { Write-Host "[dev] $msg" }

# Runs a native command and stops on a non-zero exit code. Docker writes
# progress to stderr; with 'Stop', PowerShell 5.1 would treat that as fatal.
function Invoke-Native {
  $exe, $rest = $args
  $ErrorActionPreference = 'Continue'
  & $exe @rest
  if ($LASTEXITCODE -ne 0) { Fail "'$exe $($rest -join ' ')' failed ($LASTEXITCODE)" }
}

# Reads KEY from .env without executing it.
function Get-EnvValue($key) {
  $file = Join-Path $Root '.env'
  if (-not (Test-Path $file)) { return '' }
  $line = Get-Content $file | Where-Object { $_ -match "^$key=" } | Select-Object -Last 1
  if ($line) { return ($line -replace "^$key=", '').Trim() }
  return ''
}

function Get-Slug($s) { ($s.ToLower() -replace '[^a-z0-9_-]', '-').TrimStart('-') }

function Write-Utf8($path, $text) {
  [IO.File]::WriteAllText($path, ($text -replace "`r`n", "`n"), (New-Object Text.UTF8Encoding $false))
}

# Resolves settings into .box/.env (read by compose, so VS Code sees the
# same values) and prepares DEVENV_HOME.
function Initialize-Box {
  if (-not (Get-Command docker -ErrorAction SilentlyContinue)) { Fail 'docker not found' }
  $envFile = Join-Path $Root '.env'
  if (-not (Test-Path $envFile)) {
    Copy-Item (Join-Path $Root '.env.example') $envFile
    Info 'created .env from .env.example'
  }

  $home_ = Get-EnvValue 'DEVENV_HOME'
  if (-not $home_) { $home_ = Join-Path $HOME '.agent-devbox' }
  $home_ = $home_ -replace '^~', $HOME
  $project = Get-EnvValue 'BOX_PROJECT'
  if (-not $project) { $project = Split-Path $Root -Leaf }
  $project = Get-Slug $project

  foreach ($d in 'credentials/claude', 'credentials/codex', 'credentials/gemini', 'credentials/gh', 'agentmemory', 'ssh') {
    New-Item -ItemType Directory -Force (Join-Path $home_ $d) | Out-Null
  }
  New-Item -ItemType Directory -Force (Join-Path $Root '.box/state') | Out-Null

  $globalEnv = Join-Path $home_ '.env'
  if (-not ((Test-Path $globalEnv) -and (Select-String -Quiet -Path $globalEnv -Pattern '^AGENTMEMORY_SECRET=.'))) {
    $bytes = New-Object byte[] 32
    [Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    $secret = -join ($bytes | ForEach-Object { $_.ToString('x2') })
    $existing = if (Test-Path $globalEnv) { [IO.File]::ReadAllText($globalEnv) } else { '' }
    Write-Utf8 $globalEnv "${existing}AGENTMEMORY_SECRET=$secret`n"
    Info "generated AGENTMEMORY_SECRET in $globalEnv"
  }

  $script:Project = $project
  $script:BaseImage = "agent-devbox-base:$project"
  $script:Image = "agent-devbox:$project"
  $sshPort = Get-EnvValue 'SSH_PORT'
  Write-Utf8 (Join-Path $Root '.box/.env') @"
# Generated by ./dev; do not edit (change .env instead).
BOX_PROJECT=$project
BOX_BASE_IMAGE=$($script:BaseImage)
BOX_IMAGE=$($script:Image)
DEVENV_HOME=$($home_ -replace '\\', '/')
USER_UID=1000
USER_GID=1000
SSH_PORT=$sshPort

"@

  docker network inspect $Network *> $null
  if ($LASTEXITCODE -ne 0) { Invoke-Native docker network create $Network | Out-Null }
  docker volume inspect $NixCacheVolume *> $null
  if ($LASTEXITCODE -ne 0) { Invoke-Native docker volume create $NixCacheVolume | Out-Null }
}

function Get-ComposeFiles {
  $files = @('-f', (Join-Path $Root '.box/compose.yml'))
  if ((Get-EnvValue 'ENABLE_SSH') -eq 'true') { $files += @('-f', (Join-Path $Root '.box/compose.ssh.yml')) }
  return $files
}

function Invoke-Compose { Invoke-Native docker compose @(Get-ComposeFiles) @args }

function Invoke-MemoryCompose {
  Invoke-Native docker compose -f (Join-Path $Root '.box/memory.compose.yml') --env-file (Join-Path $Root '.box/.env') @args
}

function Build-Images([switch]$Fresh) {
  Info 'building base image'
  $pull = if ($Fresh) { @('--pull') } else { @() }
  Invoke-Native docker build @pull -t $script:BaseImage -f (Join-Path $Root 'Dockerfile') $Root
  Info 'building agents image'
  $noCache = if ($Fresh) { @('--no-cache') } else { @() }
  Invoke-Compose build @noCache dev
}

function Start-Memory {
  $running = docker ps -q --filter "label=com.docker.compose.project=$MemoryProject" --filter status=running
  if ($running) { return }
  Info 'starting shared agentmemory'
  Invoke-MemoryCompose up -d --wait
}

function Wait-Ready {
  for ($i = 0; $i -lt 180; $i++) {
    $logs = docker compose @(Get-ComposeFiles) logs dev 2>$null
    if ($logs -match '\[box\] ready') { return }
    Start-Sleep -Seconds 1
  }
  Fail 'container did not become ready; check: docker compose -f .box/compose.yml logs dev'
}

function Invoke-Up($flag) {
  Initialize-Box
  Build-Images
  Start-Memory
  Invoke-Compose up -d dev
  Wait-Ready
  Info 'ready'
  '  .\dev shell      terminal in the container'
  '  .\dev code       VS Code in the container (or: Reopen in Container)'
  '  memory viewer    http://localhost:3113'
  if ($flag -eq '--code') { Invoke-Code }
}

function Invoke-Code {
  if (-not (Get-Command code -ErrorAction SilentlyContinue)) {
    Fail "VS Code CLI 'code' not on PATH; open this folder in VS Code and run 'Dev Containers: Reopen in Container'"
  }
  $hex = -join ([Text.Encoding]::UTF8.GetBytes($Root) | ForEach-Object { $_.ToString('x2') })
  & code --folder-uri "vscode-remote://dev-container+$hex/workspace"
}

function Invoke-Rebuild {
  Initialize-Box
  Build-Images -Fresh
  Start-Memory
  Invoke-Compose up -d --force-recreate dev
  Wait-Ready
  Info 'rebuilt. The shared memory server still runs its old image; restart it with .\dev memory restart'
}

function Invoke-Init($target) {
  if (-not $target) { Fail 'usage: .\dev init <path>' }
  New-Item -ItemType Directory -Force $target | Out-Null
  $target = (Resolve-Path $target).Path
  Invoke-Native docker run --rm -v "${Root}:/src:ro" -v "${target}:/dst" debian:trixie-slim `
    bash /src/.box/runtime/bin/box-apply-template /src /dst
  Copy-Item (Join-Path $Root '.box/template.lock') (Join-Path $target '.box/template.lock')
  Info "initialized $target; next: cd there and run .\dev up"
}

$cmd, $rest = $args
switch ($cmd) {
  'up' { Invoke-Up $rest }
  'down' { Initialize-Box; Invoke-Compose down }
  'shell' { Initialize-Box; Invoke-Compose exec -it dev bash }
  'code' { Invoke-Code }
  'rebuild' { Invoke-Rebuild }
  'update' { Initialize-Box; Invoke-Compose run --rm --no-deps -T dev box-update /workspace }
  'init' { Invoke-Init $rest }
  # Hidden helpers.
  'connect' { Initialize-Box; Invoke-Compose exec -T dev box-connect }
  'memory' {
    Initialize-Box
    switch ($rest) {
      'up' { Start-Memory }
      'down' { Invoke-MemoryCompose down }
      'restart' { Invoke-MemoryCompose up -d --wait --force-recreate }
      'logs' { Invoke-MemoryCompose logs -f }
      default { Fail 'usage: .\dev memory up|down|restart|logs' }
    }
  }
  { $_ -in 'help', '-h', '--help', $null } { Show-Usage }
  default { Show-Usage; exit 1 }
}
